export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const FETCH_TOKEN = "FETCH_TOKEN";

export const GET_USER_START = "GET_USER_START";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";

export const UPDATE_USER_START = "UPDATE_USER_START";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

export const GET_OLD_MESSAGES_START = "GET_OLD_MESSAGES_START";
export const GET_OLD_MESSAGES_SUCCESS = "GET_OLD_MESSAGES_SUCCESS";
export const GET_OLD_MESSAGES_FAIL = "GET_OLD_MESSAGES_FAIL";

export const DELETE_OLD_MESSAGES_START = "DELETE_OLD_MESSAGES_START";
export const DELETE_OLD_MESSAGES_SUCCESS = "DELETE_OLD_MESSAGES_SUCCESS";
export const DELETE_OLD_MESSAGES_FAIL = "DELETE_OLD_MESSAGES_FAIL";
