# Generated by Django 3.2.6 on 2021-08-25 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_message_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='handle',
        ),
    ]
